version: "3"
services:
  user-service:
    image: user-service
    container_name: user-service
    restart: always
    environment:
      - URI=mongodb+srv://bhattgaurav654:idontknow@graphql-micro.bdwiw.mongodb.net/?retryWrites=true&w=majority&ssl=true
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
    networks:
      - backend

  product-service:
    image: product-service
    container_name: product-service
    restart: always
    environment:
      - URI=mongodb+srv://bhattgaurav654:idontknow@graphql-micro.bdwiw.mongodb.net/?retryWrites=true&w=majority&ssl=true
    ports:
      - "4002:4002"
    depends_on:
      - mongodb
    networks:
      - backend

  order-service:
    image: order-service
    container_name: order-service
    restart: always
    environment:
      - URI=mongodb+srv://bhattgaurav654:idontknow@graphql-micro.bdwiw.mongodb.net/?retryWrites=true&w=majority&ssl=true
    ports:
      - "4003:4003"
    depends_on:
      - mongodb
    networks:
      - backend

  graphql-gateway:
    image: graphql-gateway
    container_name: graphql-gateway
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb_data:
